--1
SELECT tablespace_name, file_name FROM dba_data_files;
--2

CREATE TABLESPACE GAA_QDATA 
DATAFILE 'GAA_QDATA.dbf' SIZE 10M 
OFFLINE;

ALTER TABLESPACE GAA_QDATA ONLINE;

GRANT CONNECT, RESOURCE TO C##GAA;

ALTER USER C##GAA QUOTA 2M ON GAA_QDATA;


CREATE TABLE GAA_T1 (
    ID NUMBER PRIMARY KEY,
    DATA VARCHAR2(100)
) TABLESPACE GAA_QDATA;

INSERT INTO GAA_T1 (ID, DATA) VALUES (10003, 'Data 1');
INSERT INTO GAA_T1 (ID, DATA) VALUES (20003, 'Data 2');
INSERT INTO GAA_T1 (ID, DATA) VALUES (30003, 'Data 3');

commit;

--3
SELECT SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME
FROM DBA_SEGMENTS
WHERE TABLESPACE_NAME = 'GAA_QDATA';
--4
DROP TABLE GAA_T1 purge;

SELECT SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME
FROM DBA_SEGMENTS
WHERE TABLESPACE_NAME = 'GAA_QDATA';

SELECT * FROM USER_RECYCLEBIN;
--5
FLASHBACK TABLE GAA_T1 TO BEFORE DROP;

--6
BEGIN
  FOR i IN 1..10000 LOOP
    INSERT INTO GAA_T1 (ID, DATA) 
    VALUES (i, 'Data ' || i);
  END LOOP;
  COMMIT;
END;

--7
SELECT SEGMENT_NAME, EXTENT_ID, FILE_ID, BLOCK_ID, BLOCKS, BYTES
FROM DBA_EXTENTS
WHERE SEGMENT_NAME = 'GAA_T1'
  AND TABLESPACE_NAME = 'GAA_QDATA'
ORDER BY EXTENT_ID;

--8

DROP TABLESPACE GAA_QDATA INCLUDING CONTENTS AND DATAFILES;

--9

SELECT GROUP#, STATUS, MEMBERS
FROM V$LOG;

--10
SELECT GROUP#, MEMBER
FROM V$LOGFILE;

--11
select CURRENT_TIMESTAMP from dual;--01.10.25 21:25:11,482000000 EUROPE/MINSK
ALTER SYSTEM SWITCH LOGFILE; 
ALTER SYSTEM SWITCH LOGFILE;
ALTER SYSTEM SWITCH LOGFILE;
--12
ALTER DATABASE ADD LOGFILE GROUP 4 'D:/file/logfile1.log'
SIZE 50M BLOCKSIZE 512;

ALTER DATABASE ADD LOGFILE MEMBER 'D:/file/logfile2.log' to GROUP 4;
ALTER DATABASE ADD LOGFILE MEMBER 'D:/file/logfile3.log' to GROUP 4;


SELECT GROUP#, STATUS, MEMBERS
FROM V$LOG;

SELECT GROUP#, MEMBER
FROM V$LOGFILE;

ALTER SYSTEM SWITCH LOGFILE;
SELECT CURRENT_SCN FROM V$DATABASE;
SELECT FIRST_CHANGE#, NEXT_CHANGE#, STATUS FROM V$LOG;
SELECT SEQUENCE#, FIRST_CHANGE#, NEXT_CHANGE# FROM V$ARCHIVED_LOG ORDER BY SEQUENCE#;


--13

ALTER DATABASE DROP LOGFILE MEMBER  'D:/file/logfile1.log';
ALTER DATABASE DROP LOGFILE MEMBER  'D:/file/logfile2.log';
ALTER DATABASE DROP LOGFILE MEMBER  'D:/file/logfile3.LOG';
ALTER DATABASE DROP LOGFILE GROUP 4;

--14
SELECT LOG_MODE FROM V$DATABASE;

--15
SELECT MAX(SEQUENCE#) AS LAST_ARCHIVE_SEQUENCE
FROM V$ARCHIVED_LOG;

--16 cmd sqlplus / as sysdba
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;

--17

SELECT * FROM V$LOG;

ALTER SYSTEM ARCHIVE LOG CURRENT;

SELECT SEQUENCE#, NAME FROM V$ARCHIVED_LOG ORDER BY SEQUENCE# DESC;

SELECT * FROM V$ARCHIVED_LOG;

SELECT SEQUENCE#, FIRST_CHANGE#, NEXT_CHANGE# FROM V$ARCHIVED_LOG;

--18 cmd sqlplus / as sysdba
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE NOARCHIVELOG;
ALTER DATABASE OPEN;

--19
SELECT NAME FROM V$CONTROLFILE;

--20
show parameter control;
SELECT TYPE, RECORDS_TOTAL, RECORDS_USED 
FROM V$CONTROLFILE_RECORD_SECTION;
--21
SHOW PARAMETER spfile;
--22
CREATE PFILE = 'D:/file/GAA_PFILE.ORA' FROM SPFILE;

--23 
select * from V$PWFILE_USERS;

SHOW PARAMETER remote_login_passwordfile;

--24
SHOW PARAMETER diagnostic_dest;
--25
SELECT value FROM v$diag_info WHERE name = 'Diag Trace';
