alter  database open    

ALTER SYSTEM SET JOB_QUEUE_PROCESSES = 5; 
SELECT COUNT(*) FROM DBA_OBJECTS_AE WHERE OBJECT_TYPE = 'PACKAGE';
--1. Разработайте пакет выполнения заданий, в котором:
--2. Раз в неделю в определенное время выполняется копирование части данных по
--условию из одной таблицы в другую, после чего эти данные из первой таблицы
--удаляются.
--3. Необходимо проверять, было ли выполнено задание, и в какой-либо таблице
--сохранять сведения о попытках выполнения, как успешных, так и неуспешных.

--Таблицы

DROP TABLE SOURCE_TABLE;
DROP TABLE TARGET_TABLE;
DROP TABLE JOB_LOG;

CREATE TABLE SOURCE_TABLE (
    ID NUMBER PRIMARY KEY,
    DATA VARCHAR2(100)
);

CREATE TABLE TARGET_TABLE (
    ID NUMBER PRIMARY KEY,
    DATA VARCHAR2(100)
);

CREATE TABLE JOB_LOG (
    LOG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RUN_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(20),
    ERROR_MESSAGE VARCHAR2(4000)
);

BEGIN 
FOR i IN 1..200 LOOP
INSERT INTO SOURCE_TABLE VALUES(i, 'DATA ' || i);
END LOOP;
END;

--Процедура выполняемая в job

CREATE OR REPLACE PROCEDURE COPY_AND_DELETE_DATA IS
BEGIN
    -- Копируем данные
    INSERT INTO TARGET_TABLE (ID, DATA)
    SELECT ID, DATA
    FROM SOURCE_TABLE
    WHERE ID < 100; -- Условие для копирования

    -- Удаляем данные
    DELETE FROM SOURCE_TABLE
    WHERE ID < 100;

    -- Логируем успешное выполнение
    INSERT INTO JOB_LOG (STATUS)
    VALUES ('SUCCESS');
EXCEPTION
    WHEN OTHERS THEN
        -- Логируем ошибку
        INSERT INTO JOB_LOG (STATUS, ERROR_MESSAGE)
        VALUES ('FAILED', 'Ошибка в ходе выполнения задачи');
        RAISE;
END;    



-- Удалить старый джоб
BEGIN DBMS_JOB.REMOVE(42); COMMIT; END;

-- Создать новый с немедленным запуском
DECLARE v_job_id NUMBER;
BEGIN
  DBMS_JOB.SUBMIT(
    job => v_job_id,
    what => 'COPY_AND_DELETE_DATA;',
    next_date => SYSDATE + 1/1440  -- через минуту
  );
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('New Job ID: ' || v_job_id);
END;
/

-- Принудительно запустить
BEGIN DBMS_JOB.RUN(43); END;
/



--Проверка выполнения задания
SELECT JOB, LAST_DATE, NEXT_DATE, BROKEN
FROM USER_JOBS;
--4.

SELECT * FROM SOURCE_TABLE;
SELECT * FROM TARGET_TABLE;
SELECT * FROM JOB_LOG;

BEGIN
    DBMS_JOB.CHANGE(
        job        => 41,                      -- Идентификатор задания
        what       => 'BEGIN COPY_AND_DELETE_DATA; END;',  -- Блок PL/SQL, который выполняется
        next_date  => TO_DATE('2024-12-30 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), -- Новое время начала
        interval   => 'TRUNC(SYSDATE) + 7'           -- Интервал повторения, если необходимо
    );
    COMMIT;
END;

BEGIN
    DBMS_JOB.BROKEN(2, TRUE);
    COMMIT;
END;

BEGIN
    DBMS_JOB.BROKEN(2, FALSE);
    COMMIT;
END;

BEGIN
    DBMS_JOB.REMOVE(4);
    COMMIT;
END;

BEGIN
    DBMS_JOB.RUN(42);
END;

--5.

SELECT * FROM JOB_LOG
ORDER BY RUN_DATE DESC;


--6.

BEGIN
    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => 'COPY_AND_DELETE_JOB',
        job_type        => 'PLSQL_BLOCK',
        job_action      => 'BEGIN COPY_AND_DELETE_DATA; END;',
        start_date      => SYSDATE,
        repeat_interval => 'FREQ=WEEKLY; BYDAY=SUN; BYHOUR=2; BYMINUTE=0; BYSECOND=0',
        enabled         => TRUE,
        auto_drop       => FALSE,
        comments        => 'Weekly job to copy and delete data'
    );
END;

SELECT JOB_NAME, STATE, START_DATE, LAST_START_DATE, NEXT_RUN_DATE
FROM USER_SCHEDULER_JOBS
WHERE JOB_NAME = 'COPY_AND_DELETE_JOB';

BEGIN
    DBMS_SCHEDULER.RUN_JOB('COPY_AND_DELETE_JOB', TRUE);
END;

BEGIN
    DBMS_SCHEDULER.DISABLE('COPY_AND_DELETE_JOB');
END;

BEGIN
    DBMS_SCHEDULER.ENABLE('COPY_AND_DELETE_JOB');
END;

BEGIN
    DBMS_SCHEDULER.DROP_JOB('COPY_AND_DELETE_JOB');
END;

SELECT * FROM JOB_LOG ORDER BY RUN_DATE DESC;