   --1
SELECT PDB_ID, PDB_NAME, STATUS
FROM CDB_PDBS;

--2
SELECT INSTANCE_NAME, HOST_NAME, STATUS
FROM GV$INSTANCE;

--3
SELECT PRODUCT AS Компонент, VERSION AS Версия, STATUS AS Статус
FROM PRODUCT_COMPONENT_VERSION;

--4

--D:\ORACLE\ORADATA\ORCL\PDB_GAA
--5
SELECT PDB_ID, PDB_NAME, STATUS
FROM CDB_PDBS;



--6 
CREATE TABLESPACE TS_GAA_PDB 
    DATAFILE 'D:\file\TS_GAA_PDB.dbf' 
    SIZE 100M 
    AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE ROLE RL_GAA_PDB;
GRANT CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE PROCEDURE
    TO RL_GAA_PDB;

CREATE PROFILE PF_GAA_PDB LIMIT 
    SESSIONS_PER_USER 5 
    FAILED_LOGIN_ATTEMPTS 3 
    PASSWORD_LIFE_TIME 30;


CREATE USER U1_GAA_PDB IDENTIFIED BY Gritsenko
    DEFAULT TABLESPACE TS_GAA_PDB
    TEMPORARY TABLESPACE TEMP
    PROFILE PF_GAA_PDB;
    GRANT 
--7
GRANT CREATE SESSION TO U1_GAA_PDB
CREATE TABLE GAA_TABLE (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100)
);

INSERT INTO GAA_TABLE (id, name) VALUES (1, 'Item1');
INSERT INTO GAA_TABLE (id, name) VALUES (2, 'Item2');
INSERT INTO GAA_TABLE (id, name) VALUES (3, 'Item3');

SELECT * FROM GAA_TABLE;

--8
ALTER pluggable database GAA_PBD open;
SELECT TABLESPACE_NAME, STATUS, CONTENTS FROM DBA_TABLESPACES;

SELECT FILE_NAME, TABLESPACE_NAME, BYTES, MAXBYTES 
FROM DBA_DATA_FILES;

SELECT FILE_NAME, TABLESPACE_NAME, BYTES, MAXBYTES 
FROM DBA_TEMP_FILES;

SELECT ROLE FROM DBA_ROLES;

SELECT GRANTEE, PRIVILEGE, TABLE_NAME
FROM DBA_TAB_PRIVS
WHERE GRANTEE IN (SELECT ROLE FROM DBA_ROLES);

SELECT PROFILE, RESOURCE_NAME, LIMIT FROM DBA_PROFILES;

SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS;
SELECT GRANTEE FROM DBA_ROLE_PRIVS;

--9
CREATE USER C##GAA IDENTIFIED BY Gritsenko;
GRANT CONNECT, RESOURCE TO C##GAA;
GRANT CREATE SESSION TO C##GAA;
--10
ALTER PLUGGABLE DATABASE GAA_PBD CLOSE IMMEDIATE;

DROP PLUGGABLE DATABASE GAA_PBD INCLUDING DATAFILES;
DROP USER C##GAA CASCADE;
