-- 1
CREATE TABLESPACE TS_GAA 
DATAFILE 'D:\file\TS_GAA.dbf' SIZE 7M 
AUTOEXTEND ON NEXT 5M MAXSIZE 20M;

-- 2
CREATE TEMPORARY TABLESPACE TS_GAA_TEMP 
TEMPFILE 'D:\file\TS_GAA_TEMP.dbf' SIZE 5M 
AUTOEXTEND ON NEXT 3M MAXSIZE 30M;

--3 
SELECT FILE_NAME, TABLESPACE_NAME FROM DBA_DATA_FILES;

--4
CREATE ROLE C##R_GAACORE;
GRANT CONNECT TO  C##R_GAACORE;
GRANT CREATE TABLE, DROP ANY TABLE TO C##R_GAACORE;
GRANT CREATE VIEW, DROP ANY VIEW TO  C##R_GAACORE;
GRANT CREATE PROCEDURE, DROP ANY PROCEDURE TO  C##R_GAACORE;

--5
SELECT * FROM DBA_ROLES WHERE ROLE like 'C##R_GAACORE';

SELECT * 
FROM DBA_SYS_PRIVS,DBA_ROLES;


--6
CREATE PROFILE C##PF_GAACORE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 3
    FAILED_LOGIN_ATTEMPTS 7
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;

--7
SELECT PROFILE FROM dba_profiles;

SELECT * FROM dba_profiles WHERE PROFILE = 'C##PF_GAACORE';

SELECT * FROM dba_profiles WHERE PROFILE = 'DEFAULT';

--8
CREATE USER C##GAACORE
    DEFAULT TABLESPACE TS_GAA
    TEMPORARY TABLESPACE TS_GAA_TEMP
    PROFILE C##PF_GAACORE
    ACCOUNT UNLOCK;
    PASSWORD EXPIRE;
    
    GRANT CREATE SESSION TO C##GAACORE;
        

--9 sqlplus
sqlplus sys as sysdba

ALTER USER C##GAACORE IDENTIFIED BY Gritz;
EXIT;

sqlplus GAACORE/Gritz;

--10
CREATE TABLE GAA_T (
    ID INT PRIMARY KEY,
    Name VARCHAR(100),
    Location VARCHAR(100),
    Price INT
);

INSERT INTO GAA_T (ID, Name, Location, Price) 
VALUES (1, 'Yacht Club A', 'Lake A', 150);

INSERT INTO GAA_T (ID, Name, Location, Price) 
VALUES (2, 'Yacht Club B', 'Lake B', 200);

INSERT INTO GAA_T (ID, Name, Location, Price) 
VALUES (3, 'Yacht Club C', 'Lake C', 250);

INSERT INTO GAA_T (ID, Name, Location, Price) 
VALUES (4, 'Yacht Club D', 'Lake D', 300);

INSERT INTO GAA_T (ID, Name, Location, Price) 
VALUES (5, 'Yacht Club E', 'Lake E', 350);

--11

CREATE TABLESPACE GAA_QDATA
DATAFILE 'D:\file\GAA_QDATA.dbf' SIZE 10m
OFFLINE;

CREATE USER GAA IDENTIFIED BY SUPERSTAR
DEFAULT TABLESPACE GAA_QDATA
TEMPORARY TABLESPACE TS_GAA_TEMP;
GRANT CREATE SESSION, CREATE TABLE TO GAA;

ALTER TABLESPACE GAA_QDATA ONLINE;
ALTER USER GAA QUOT 2M ON GAA_QDATA;
CONNECT GAA/SUPERSTAR; 

CREATE TABLE XXX_T1 (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(50),
    value NUMBER
) TABLESPACE GAA_QDATA;

INSERT INTO XXX_T1 (id, name, value) VALUES (1, ',Q', 100);
INSERT INTO XXX_T1 (id, name, value) VALUES (2, 'Q2', 200);
INSERT INTO XXX_T1 (id, name, value) VALUES (3, 'Q3', 300);

COMMIT;

SELECT * FROM XXX_T1;