--  1
drop TABLE STUDENT;
alter database open;
select * from STUDENT;
CREATE TABLE STUDENT (
    STUDENT_ID NUMBER PRIMARY KEY,       
    STUDENT_NAME VARCHAR2(100) NOT NULL, 
    STUDENT_AGE NUMBER NOT NULL,    
    ENROLL_DATE DATE NOT NULL          
);

--2
INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_AGE, ENROLL_DATE) 
VALUES (1, 'Ivanov Ivan', 20, TO_DATE('2022-09-01', 'YYYY-MM-DD'));

INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_AGE, ENROLL_DATE) 
VALUES (2, 'Petrova Olga', 19, TO_DATE('2023-01-15', 'YYYY-MM-DD'));

INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_AGE, ENROLL_DATE) 
VALUES (3, 'Sidorov Alexey', 21, TO_DATE('2021-06-20', 'YYYY-MM-DD'));

INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_AGE, ENROLL_DATE) 
VALUES (4, 'Nikolaeva Anna', 22, TO_DATE('2020-03-10', 'YYYY-MM-DD'));

INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_AGE, ENROLL_DATE) 
VALUES (5, 'Kuznetsov Dmitry', 20, TO_DATE('2022-11-30', 'YYYY-MM-DD'));

INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_AGE, ENROLL_DATE) 
VALUES (6, 'Fedorova Elena', 18, TO_DATE('2023-08-25', 'YYYY-MM-DD'));

INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_AGE, ENROLL_DATE) 
VALUES (7, 'Smirnov Sergey', 23, TO_DATE('2019-12-15', 'YYYY-MM-DD'));

INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_AGE, ENROLL_DATE) 
VALUES (8, 'Alexeev Nikolay', 19, TO_DATE('2023-05-05', 'YYYY-MM-DD'));

INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_AGE, ENROLL_DATE) 
VALUES (9, 'Popova Maria', 21, TO_DATE('2021-07-14', 'YYYY-MM-DD'));

INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_AGE, ENROLL_DATE) 
VALUES (11, 'Vasilyeva Anna', 20, TO_DATE('2022-04-18', 'YYYY-MM-DD'));

COMMIT;

--3
BEGIN
    DBMS_OUTPUT.ENABLE;
END;
/

--4
CREATE OR REPLACE TRIGGER STUDENT_OP_BEFORE
BEFORE INSERT OR DELETE OR UPDATE
ON STUDENT
DECLARE
    v_operation VARCHAR2(10);
BEGIN
    DBMS_OUTPUT.PUT_LINE('Trigger STUDENT_OP_BEFORE: delete or insert or update in student ');
END;
/

--5
CREATE OR REPLACE TRIGGER STUDENT_ROW_BEFORE
BEFORE INSERT OR DELETE OR UPDATE
ON STUDENT
FOR EACH ROW
BEGIN
        DBMS_OUTPUT.PUT_LINE('TRIGGER STUDENT_ROW_BEFORE:  ID = ' || :NEW.STUDENT_ID);
END;
/

--6

CREATE OR REPLACE TRIGGER STUDENT_ROW_BEFORE
BEFORE INSERT OR DELETE OR UPDATE
ON STUDENT
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        DBMS_OUTPUT.PUT_LINE('Триггер STUDENT_ROW_BEFORE: вставлена новая запись с ID = ' || :NEW.STUDENT_ID);
    ELSIF UPDATING THEN
        DBMS_OUTPUT.PUT_LINE('Триггер STUDENT_ROW_BEFORE: обновлена запись с ID = ' || :OLD.STUDENT_ID);
    ELSIF DELETING THEN
        DBMS_OUTPUT.PUT_LINE('Триггер STUDENT_ROW_BEFORE: удалена запись с ID = ' || :OLD.STUDENT_ID);
    END IF;
END;
/


--7

CREATE OR REPLACE TRIGGER STUDENT_OP_AFTER
AFTER INSERT OR DELETE OR UPDATE
ON STUDENT
DECLARE
    v_operation VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_operation := 'INSERT';
    ELSIF DELETING THEN
        v_operation := 'DELETE';
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
    END IF;

    DBMS_OUTPUT.PUT_LINE('Триггер STUDENT_OP_AFTER: выполнена операция ' || v_operation);
END;
/


--8

CREATE OR REPLACE TRIGGER STUDENT_ROW_AFTER
AFTER INSERT OR DELETE OR UPDATE
ON STUDENT
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        DBMS_OUTPUT.PUT_LINE('Триггер STUDENT_ROW_AFTER: вставлена запись с ID = ' || :NEW.STUDENT_ID);
    ELSIF UPDATING THEN
        DBMS_OUTPUT.PUT_LINE('Триггер STUDENT_ROW_AFTER: обновлена запись с ID = ' || :OLD.STUDENT_ID);
    ELSIF DELETING THEN
        DBMS_OUTPUT.PUT_LINE('Триггер STUDENT_ROW_AFTER: удалена запись с ID = ' || :OLD.STUDENT_ID);
    END IF;
END;
/

INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_AGE, ENROLL_DATE) 
VALUES (16, 'Vasilyev Alexey', 20, TO_DATE('2022-04-18', 'YYYY-MM-DD'));

--9
CREATE TABLE AUDIT_LOG (
    OperationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OperationType VARCHAR2(10),
    TriggerName VARCHAR2(50),
    Data CLOB
);


--10
CREATE OR REPLACE TRIGGER STUDENT_ROW_BEFORE
BEFORE INSERT OR DELETE OR UPDATE
ON STUDENT
FOR EACH ROW
DECLARE
 v_operation VARCHAR2(10);
BEGIN
IF INSERTING THEN
        v_operation := 'INSERT';
    ELSIF DELETING THEN
        v_operation := 'DELETE';
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
    END IF;
    DBMS_OUTPUT.PUT_LINE('STUDENT_ROW_BEFORE: ' || v_operation);

    INSERT INTO AUDIT_LOG (OperationType, TriggerName, Data)
    VALUES (v_operation, 'STUDENT_ROW_BEFORE', 'Operation performed on STUDENT table');
END;
/


CREATE OR REPLACE TRIGGER STUDENT_ROW_AFTER
AFTER INSERT OR DELETE OR UPDATE
ON STUDENT
FOR EACH ROW
DECLARE 
    v_operation VARCHAR2(10);
BEGIN
IF INSERTING THEN
        v_operation := 'INSERT';
    ELSIF DELETING THEN
        v_operation := 'DELETE';
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
    END IF;
    DBMS_OUTPUT.PUT_LINE('STUDENT_ROW_AFTER: ' || v_operation);

    INSERT INTO AUDIT_LOG (OperationType, TriggerName, Data)
    VALUES (v_operation, 'STUDENT_ROW_AFTER', 'Operation performed on STUDENT table');
END;
/

CREATE OR REPLACE TRIGGER STUDENT_OP_AFTER
AFTER INSERT OR DELETE OR UPDATE
ON STUDENT
DECLARE
    v_operation VARCHAR2(10);
BEGIN

    IF INSERTING THEN
        v_operation := 'INSERT';
    ELSIF DELETING THEN
        v_operation := 'DELETE';
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
    END IF;
    DBMS_OUTPUT.PUT_LINE('STUDENT_OP_AFTER: ' || v_operation);

    INSERT INTO AUDIT_LOG (OperationType, TriggerName, Data)
    VALUES (v_operation, 'STUDENT_OP_AFTER', 'Operation performed on STUDENT table');
END;
/

CREATE OR REPLACE TRIGGER STUDENT_OP_BEFORE
BEFORE INSERT OR DELETE OR UPDATE
ON STUDENT
DECLARE
    v_operation VARCHAR2(10);
BEGIN

    IF INSERTING THEN
        v_operation := 'INSERT';
    ELSIF DELETING THEN
        v_operation := 'DELETE';
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
    END IF;
    DBMS_OUTPUT.PUT_LINE('STUDENT_OP_BEFORE: ' || v_operation);

    INSERT INTO AUDIT_LOG (OperationType, TriggerName, Data)
    VALUES (v_operation, 'STUDENT_OP_BEFORE', 'Operation performed on STUDENT table');
END;
/

--11

INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_AGE, ENROLL_DATE) 
VALUES (13, 'Sidorov Alexey', 21, TO_DATE('2021-06-20', 'YYYY-MM-DD'));

INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_AGE, ENROLL_DATE) 
VALUES (13, 'Sidorov Alexey', 21, TO_DATE('2021-06-20', 'YYYY-MM-DD'));


DELETE FROM STUDENT WHERE STUDENT_ID = 13;

INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_AGE, ENROLL_DATE) 
VALUES (17, 'Sidorov Alexey', 21, TO_DATE('2021-06-20', 'YYYY-MM-DD'));

select * from AUDIT_LOG;
--12

DROP TABLE STUDENT;
CREATE OR REPLACE TRIGGER PREVENT_DROP_SCHEMA_TRIGGER
BEFORE DROP ON SCHEMA
BEGIN
    IF ORA_DICT_OBJ_NAME = 'STUDENT' THEN
        RAISE_APPLICATION_ERROR(-20001, 'Удаление таблицы STUDENT запрещено!');
    END IF;
END;
/


--13

DROP TABLE AUDIT_LOG;

--14
drop view student_view;

CREATE OR REPLACE VIEW STUDENT_VIEW AS
SELECT STUDENT_ID, STUDENT_NAME, STUDENT_AGE, ENROLL_DATE FROM STUDENT;


CREATE OR REPLACE TRIGGER STUDENT_VIEW_INSERT
INSTEAD OF INSERT
ON STUDENT_VIEW
FOR EACH ROW
BEGIN
    INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_AGE, ENROLL_DATE)
    VALUES (:NEW.STUDENT_ID, :NEW.STUDENT_NAME, :NEW.STUDENT_AGE, :NEW.ENROLL_DATE);
END;
/

INSERT INTO STUDENT_VIEW (STUDENT_ID, STUDENT_NAME, STUDENT_AGE, ENROLL_DATE) 
VALUES (18, 'Vasilyev Alexey', 20, TO_DATE('2022-04-18', 'YYYY-MM-DD'));

select * from STUDENT;

commit;
